import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  const [formData, setFormData] = useState({
    firstName: '',
    username: ''
  })

  const CheckLogin = () => {
    console.log(formData.firstName);
    console.log(formData);

    if(formData.username !== null){
      router.push({
        pathname: './counter',
        query: {
          username: formData.username
        }
      })
    }
  }

  return (
    <>
      <Head>
        <title>LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      <div className={styles.inputs}>

        <div className={styles.firstBar}>
        <label>First name:</label>
        <input className={styles.inputOne}
          type="text"
          id="first"
          name="first"
          pattern="[A-Z]{1}[a-z]{2, 10}"
          title="The first letter should be uppercase"
          onChange={(e => setFormData({...formData, firstName: e.target.value}))}
        />
      </div>

      <div className={styles.secondBar}>
        <label>Username:</label>
        <input className={styles.inputTwo}
          type="text"
          id="username"
          name="username"
          required
          minLength="5"
          maxLength="10"
          onChange={(e => setFormData({...formData, username: e.target.value}))}
        />
      </div>
    </div>


         <button className={styles.btn} type="submit" onClick={() => CheckLogin()}>Submit</button>
      </main>
    </>
  )
}
